# Generated by Django 3.0.9 on 2020-08-04 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200804_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='Uncategorized', on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
    ]
