# Generated by Django 3.1 on 2020-08-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200805_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='course',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
