# Generated by Django 3.0.9 on 2020-08-04 12:40

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200804_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=blog.models.Category, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
    ]
